apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloweb
  annotations:
    kubernetes.io/ingress.global-static-ip-name: '{{repl ConfigOption "helloweb_ip" }}'
    kubernetes.io/ingress.class: "nginx"  
    cert-manager.io/issuer: "letsencrypt-prod"
  labels:
    app: hello
spec:
  backend:
    serviceName: helloweb-backend
    servicePort: 8080
  tls:
  - secretName: hello2-materiography-com-tls
    hosts:
    - hello2.materiography.com
  rules:
  - host: hello2.materiography.com
    http:
      paths:
      - path: /
        backend:
          serviceName: helloweb
          servicePort: 80